NUmPy stands for numerical python
numpy can be installed with conda or with pip
    conda:  an open source , cross platform package manager used toinstall , run, and update packages
    pip : pip is a package manager for pyhton that is used to install additional libraries,

In [1]:
import numpy as np
arr = np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


In [4]:
array_2d = np.array([[1,2],[3,4],[5,6]])
[m,n] = [array_2d.shape[0],array_2d.shape[1]]

array_size = array_2d.shape
m= array_2d.shape[0]
n= array_2d.shape[1]

print(array_size)
print(m)
print(n)

(3, 2)
3
2


In [9]:
a = np.arange(10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [10]:
c= np.arange(1, 10, dtype = float)
print(c)

[1. 2. 3. 4. 5. 6. 7. 8. 9.]


In [11]:
d = np.arange(2,20,3)
print(d)

[ 2  5  8 11 14 17]


In [12]:
array_2d = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(array_2d)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [13]:
print(array_2d[0,:])
print(array_2d[1,:])
print(array_2d[2,:])

[1 2 3]
[4 5 6]
[7 8 9]


In [14]:
print(array_2d[:,0])
print(array_2d[:,1])
print(array_2d[:,2])

[1 4 7]
[2 5 8]
[3 6 9]


In [15]:
Mat1 = np.arange(16).reshape(4,4)
print(Mat1)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [16]:
SubMat1 = Mat1[:2,:2]
print(SubMat1)

[[0 1]
 [4 5]]


In [17]:
SubMat2 = Mat1[1:4,1:4]
print(SubMat2)

[[ 5  6  7]
 [ 9 10 11]
 [13 14 15]]
