(1) Write a Python program that executes an operation on a list and handles an ‘IndexError’ exception if the index is out of range.

In [1]:
def get_element_from_list(lst, index):
    try:
        # Attempt to access the element at the given index
        element = lst[index]
        print(f"Element at index {index}: {element}")
    except IndexError:
        # Handle the case where the index is out of range
        print(f"Error: Index {index} is out of range for the list.")

# Example usage
my_list = [10, 20, 30, 40, 50]
index_to_access = 5  # This index is out of range for the given list

get_element_from_list(my_list, index_to_access)


Error: Index 5 is out of range for the list.


(2) Write a program that divides two numbers provided by the user. The program should handle the following exceptions:

(a) a ‘ValueError; if the user does not enter a number.

(b) ‘ZeroDivisionError’ if the user attempts to divide by zero.

(c) An unexpected exception using a generic Exception handler.

In [2]:
def divide_numbers():
    try:
        num1 = float(input("Enter the first number: "))
        num2 = float(input("Enter the second number: "))

        result = num1 / num2
        print(f"The result of {num1} divided by {num2} is {result}")

    except ValueError:
        print("Error: Please enter a valid number.")
    
    except ZeroDivisionError:
        print("Error: Division by zero is not allowed.")
    
    except Exception as e:
        print(f"An unexpected error occurred: {e}")
        
divide_numbers()


The result of 54.0 divided by 89.0 is 0.6067415730337079


(3) Write a function get_integer_input(prompt) that prompts the user to enter an integer. If the user enters anything other than an integer 
(e.g., a string like ‘five’), the function should catch the ValueError and prompt the user again until a valid integer is entered. The function should return a valid integer.

In [4]:
def get_integer_input(prompt):
    while True:
        try:
            # Prompt the user to enter an integer
            user_input = int(input(prompt))
            return user_input
        except ValueError as e:
            # Handle the ValueError if the input is not an integer
            print(f"Error: '{e.args[0].split(':')[1].strip()}' is not a valid integer. Please enter a number.")

# Example usage
result = get_integer_input("Please enter an integer: ")
print(f"You entered the integer: {result}")


Error: ''84.365'' is not a valid integer. Please enter a number.
Error: ''89.65'' is not a valid integer. Please enter a number.
You entered the integer: 54


(4) Write a function validate_user_input(str) that takes a string as input and checks the following:

(a) The string must be at least 8 characters long.

(b) The string must contain at least one digit.

(c) The string must contain at least one uppercase letter.

If any of these conditions are not met, the function should raise a custom exception InvalidInputError with a message specifying which condition failed.

In [5]:
class InvalidInputError(Exception):
    """Custom exception for invalid user input."""
    pass

def validate_user_input(input_str):
    if len(input_str) < 8:
        raise InvalidInputError("The string must be at least 8 characters long.")
    
    if not any(char.isdigit() for char in input_str):
        raise InvalidInputError("The string must contain at least one digit.")
    
    if not any(char.isupper() for char in input_str):
        raise InvalidInputError("The string must contain at least one uppercase letter.")
    
    print("The input is valid.")

# Example usage
try:
    user_input = input("Enter a string to validate: ")
    validate_user_input(user_input)
except InvalidInputError as e:
    print(f"Validation failed: {e}")


The input is valid.


(5) Write a Python program for an interactive calculator that:

(a) Continuously prompts the user to enter a simple arithmetic formula con-
sisting of a number, an operator (+ or -), and another number, all sepa-
rated by spaces (e.g., "3 + 5").

(b) Splits the user input using str.split() and checks if the input is valid. The
input is valid if:
(i) It consists of exactly three elements.

(ii) The first and third elements can be converted to floating-point num-
bers.

(iii) The second element is either ’+’ or ’-’.
(c) If the input is invalid, the program should raise a FormulaError, a custom
exception, with an appropriate error message.
(d) If the input is valid, the program should perform the calculation and
print the result.
(e) The program should keep running until the user types "quit".

In [6]:
class FormulaError(Exception):
    """Custom exception for invalid arithmetic formulas."""
    pass

def evaluate_formula(formula):
    try:
        # Split the formula into components
        parts = formula.split()

        # Check if the formula has exactly three parts
        if len(parts) != 3:
            raise FormulaError("The formula must consist of exactly three parts: number operator number")

        num1, operator, num2 = parts

        # Convert the first and third parts to floats
        try:
            num1 = float(num1)
            num2 = float(num2)
        except ValueError:
            raise FormulaError("The first and third elements must be numbers")

        # Check if the operator is valid
        if operator not in ('+', '-'):
            raise FormulaError("The operator must be either '+' or '-'")

        # Perform the calculation
        if operator == '+':
            result = num1 + num2
        else:  # operator == '-'
            result = num1 - num2

        return result

    except FormulaError as e:
        print(f"Invalid formula: {e}")
        return None

def interactive_calculator():
    while True:
        user_input = input("Enter a simple arithmetic formula (or type 'quit' to exit): ")

        if user_input.lower() == 'quit':
            print("Exiting calculator.")
            break

        result = evaluate_formula(user_input)

        if result is not None:
            print(f"Result: {result}")

# Example usage
interactive_calculator()


Invalid formula: The formula must consist of exactly three parts: number operator number
Invalid formula: The formula must consist of exactly three parts: number operator number
Result: 119.0
Invalid formula: The formula must consist of exactly three parts: number operator number
Result: 141.0
Exiting calculator.


(6) Write a Python program that matches a string that has the letter ‘a’ followed
by zero or more b’s.

In [7]:
import re

def match_ab(string):
    # Regular expression pattern for 'a' followed by zero or more 'b's
    pattern = r'^ab*$'
    
    # Use re.match to check if the entire string matches the pattern
    if re.match(pattern, string):
        return "Match found!"
    else:
        return "No match found."

# Example usage
print(match_ab("a"))       # Match found!
print(match_ab("ab"))      # Match found!
print(match_ab("abb"))     # Match found!
print(match_ab("ac"))      # No match found
print(match_ab("aabb"))    # No match found


Match found!
Match found!
Match found!
No match found.
No match found.


(7) Write a Python program to find the sequences of one upper case letter followed
by lower case letters.

In [8]:
import re

def find_uppercase_sequences(string):
    # Regular expression pattern for an uppercase letter followed by lowercase letters
    pattern = r'[A-Z][a-z]+'
    
    # Use re.findall to find all matching sequences in the string
    matches = re.findall(pattern, string)
    
    return matches

# Example usage
input_string = "Hello World This is A Test"
sequences = find_uppercase_sequences(input_string)
print("Found sequences:", sequences)


Found sequences: ['Hello', 'World', 'This', 'Test']


(8) Write a Python program that matches a word at the beginning of a string.

In [9]:
import re

def match_word_at_start(string):
    # Regular expression pattern to match a word at the beginning of the string
    pattern = r'^\w+'
    
    # Use re.match to check if the string starts with a word
    match = re.match(pattern, string)
    
    if match:
        return f"Match found: '{match.group()}'"
    else:
        return "No match found."

input_string = "Hello World!"
result = match_word_at_start(input_string)
print(result)


Match found: 'Hello'


(9) Write a function validate_email(email) that checks if a given email address
is valid using regular expressions. A valid email should follow this format:

(a) It should start with one or more alphanumeric characters or underscores.

(b) It should contain exactly one ’@’ symbol.

(c) It should then contain one or more alphanumeric characters.

(d) It should end with a valid domain name (e.g., .com, .org, .edu).

If the email is not valid, raise a custom InvalidEmailError exception with an
appropriate error message.

In [10]:
import re

class InvalidEmailError(Exception):
    """Custom exception for invalid email addresses."""
    pass

def validate_email(email):
    # Regular expression pattern for validating an email address
    pattern = r'^[a-zA-Z0-9_]+@[a-zA-Z0-9]+\.[a-zA-Z]{2,}$'
    
    # Use re.match to check if the email matches the pattern
    if not re.match(pattern, email):
        raise InvalidEmailError(f"'{email}' is not a valid email address.")
    
    return f"'{email}' is a valid email address."

try:
    email = "test_user@example.com"
    print(validate_email(email))
    
    invalid_email = "invalid-email.com"
    print(validate_email(invalid_email))  # This will raise InvalidEmailError
except InvalidEmailError as e:
    print(e)

'test_user@example.com' is a valid email address.
'invalid-email.com' is not a valid email address.


(10) Write a function that checks if a password is strong using regular expressions.
A strong password should:

(a) Be at least 8 characters long.

(b) Contain both uppercase and lowercase letters.

(c) Include at least one digit.

(d) Have at least one special character (e.g., @, #, $).

If the password is not strong enough, raise a custom ‘WeakPasswordError’
exception with a message indicating which criteria were not met.

In [11]:
import re

class WeakPasswordError(Exception):
    """Custom exception for weak passwords."""
    pass

def check_strong_password(password):
    # Criteria for a strong password
    if len(password) < 8:
        raise WeakPasswordError("Password must be at least 8 characters long.")
    
    if not re.search(r'[A-Z]', password):
        raise WeakPasswordError("Password must contain at least one uppercase letter.")
    
    if not re.search(r'[a-z]', password):
        raise WeakPasswordError("Password must contain at least one lowercase letter.")
    
    if not re.search(r'[0-9]', password):
        raise WeakPasswordError("Password must contain at least one digit.")
    
    if not re.search(r'[!@#$%^&*(),.?":{}|<>]', password):
        raise WeakPasswordError("Password must contain at least one special character.")
    
    return "Password is strong."

# Example usage
try:
    password = "StrongPass123!"
    print(check_strong_password(password))
    
    weak_password = "weakpass"
    print(check_strong_password(weak_password))  # This will raise WeakPasswordError
except WeakPasswordError as e:
    print(e)


Password is strong.
Password must contain at least one uppercase letter.


(11) Write a NumPy program to test whether none of the elements of a given array
are zero.

In [12]:
import numpy as np

array = np.array([1, 2, 3, 4, 5])

result = np.all(array != 0)

print(result)

True


(12) Write a NumPy program to create a 10x10 matrix, in which the elements on
the borders will be equal to 1, and inside 0.

In [13]:
import numpy as np

# Create a 10x10 matrix filled with zeros
matrix = np.zeros((10, 10), dtype=int)

# Set the border elements to 1
matrix[0, :] = 1          # Top border
matrix[-1, :] = 1         # Bottom border
matrix[:, 0] = 1          # Left border
matrix[:, -1] = 1         # Right border

print(matrix)

[[1 1 1 1 1 1 1 1 1 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 1 1 1 1 1 1 1 1 1]]


(13) Write a NumPy program to calculate the absolute value element-wise.

In [15]:
import numpy as np

arr = np.array([-10.2, 122.2, 0.2])

abs_arr = np.abs(arr)

print("Original array:")
print(arr)
print("Element-wise absolute value:")
print(abs_arr)

Original array:
[-10.2 122.2   0.2]
Element-wise absolute value:
[ 10.2 122.2   0.2]


(14) Write a NumPy program to compute the inner product of two given vectors.

In [17]:
import numpy as np

# Define two vectors
vector1 = np.array([1, 2, 3])
vector2 = np.array([4, 5, 6])

# Compute the inner product
inner_product = np.dot(vector1, vector2)

print("Inner Product:", inner_product)


Inner Product: 32


(15) Write a NumPy program to find the inverse of a given matrix.

In [18]:
import numpy as np

matrix = np.array([[1, 2, 3],
                   [0, 1, 4],
                   [5, 6, 0]])

inverse_matrix = np.linalg.inv(matrix)

print("Original Matrix:")
print(matrix)
print("\nInverse Matrix:")
print(inverse_matrix)


Original Matrix:
[[1 2 3]
 [0 1 4]
 [5 6 0]]

Inverse Matrix:
[[-24.  18.   5.]
 [ 20. -15.  -4.]
 [ -5.   4.   1.]]
